routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware'=>['auth','web','member']],function(){
    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/', 'HomeController@index');
    Route::get('/client', 'HomeController@index');
    $routes_path = base_path('routes');
    $route_files = File::allFiles(base_path('routes'));
    foreach($route_files as $file){
        $path = $file->getPath();
        if($path != $routes_path){
            $file_name = $file->getFileName();
            $prefix = str_replace($file_name,'',$path);
            $prefix = str_replace($routes_path,'',$prefix);
            $file_path = $file->getPathName();
            $this->route_path = $file_path;
            $arr = explode('/',$prefix);
            $len = count($arr);
            $main_file= $arr[$len-1];
            $arr = array_map('ucwords',$arr);
            $arr = array_filter($arr);
            $ext_route = str_replace('index.route.php','',$file_name);
            $ext_route = str_replace($main_file,'',$ext_route);
            $ext_route = str_replace('.route.php','',$ext_route);
            $ext_route = str_replace('web','',$ext_route);
            if($ext_route)
                $ext_route = '/'.$ext_route;
            Route::group(['namespace'=>implode('\\',$arr),'prefix'=>strtolower($prefix.$ext_route)],function(){
                require $this->route_path;
            });
        }
    }
});

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('register/{id}','HomeController@register');

Route::resource('houses', 'HousesController');

app/Http/Controllers/Admin/HousesController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\House;
use App\Models\HouseType;
use App\Repositories\SearchRepo;

class HousesController extends Controller
{
        public function index(){
        return view($this->folder.'houses',[

        ]);
    }


    public function storeHouse(){
        request()->validate($this->getValidationFields());
        $data = \request()->all();        
        $data['user_id'] = request()->user()->id;
        if(request()->file('image')){
            $file = request()->file('image');
            $file_name = $file->getClientOriginalName();
//            $name_arr = explode('.',$file_name);
//            $ext = $name_arr[count($name_arr)-1];
//            $file_name = str_replace($ext,'',$file_name);
//            $file_name = str_slug($file_name).'.'.$ext;
            $file_name = time().'-'.str_random(5).'-'.$file_name;
            $file->move(storage_path('app/public/house-images'),$file_name);
            $file_path = 'storage/house-images/'.$file_name;
            $data['image'] = $file_path;
        }
        $this->autoSaveModel($data);

        return redirect()->back();
    }

    public function listHouses(){
        $houses = House::join('house_types','house_types.id','=','houses.house_type_id')->where([
            ['houses.id','>',0]
        ])->select('houses.*','house_types.type as house_type');
        if(\request('all'))
            //return $houses->get();
            return $houses->select('houses.id','house_name as name')->get();
        return SearchRepo::of($houses)
            ->addColumn('image',function($house){
                if($house->image)
                    return '<img style="height:150px;" src="'.url($house->image).'">';
                return 'N/A';
            })
            ->addColumn('action',function($house){
                $str = '';
                $json = json_encode($house);
                $str.='<a href="#" data-model="'.htmlentities($json, ENT_QUOTES, 'UTF-8').'" onclick="prepareEdit(this,\'house_modal\');" class="btn btn-info btn-xs"><i class="fa fa-edit"></i> Edit</a>';
                return $str;
            })->make();
    }
}

app/Http/Controllers/HousesController.php
<?php

namespace App\Http\Controllers;

use App\Models\House;
use App\Models\HouseType;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class HousesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $houses=House::all();

        if(Auth::check()){

        $houses=House::where('user_id',Auth::user()->id)->get();
        return view('houses.index',['houses'=>$houses]);
        }
       return view('auth.login');
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($house_type_id=null)
    {
        //

        $houseTypes=null;

        if(!$house_type_id){
            $houseTypes=HouseType::all();

        }

        return view('houses.create',['house_type_id'=>$house_type_id,'houseTypes'=>$houseTypes]);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //

        if(Auth::check()){
            $house=House::create([
                'house_type_id'=>$request->input('house_type_id'),
                'house_name'=>$request->input('house_name'),
                'house_description'=>$request->input('house_description'),
                'state'=>$request->input('state'),
                'city'=>$request->input('city'),
                'area'=>$request->input('area'),
                'latitude'=>$request->input('latitude'),
                'longitude'=>$request->input('longitude'),
                'no_rooms'=>$request->input('no_rooms'),
                'user_id'=>Auth::user()->id

            ]);

            if($house){
                return redirect()->route('houses.show',['house'=>$house->id])->with('success','house created successifully');
            }

        }

        return back()->with('errors','Error creating new house');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\house  $house
     * @return \Illuminate\Http\Response
     */
    public function show(house $house)
    {
        //
        $house=House::find($house->id);
        return view('houses.show',['house'=>$house]);
        // return view('houses.show',compact('house'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\house  $house
     * @return \Illuminate\Http\Response
     */
    public function edit(house $house)
    {
        //
        $house=House::find($house->id);
        return view('houses.edit',['house'=>$house]);
    }



    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\house  $house
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, house $house)
    {
        //save data
        $houseUpdate=House::where('id',$house->id)->update([

            'house_type_id'=>$request->input('house_type_id'),
            'house_name'=>$request->input('house_name'),
            'house_no_rooms'=>$request->input('house_no_rooms'),
            'house_category'=>$request->input('house_category'),
            'house_description'=>$request->input('house_description'),
            'price'=>$request->input('price'),
            'location_id'=>$request->input('location_id'),

        ]);

        if($houseUpdate){
            return redirect()->route('houses.show',['house'=>$house->id])->with('success','house updated successifuly');
        }

        //redirect
        return back()->withInput();


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\house  $house
     * @return \Illuminate\Http\Response
     */
    public function destroy(house $house)
    {
        //
        $findhouse=House::find($house->id);
        if($findhouse->delete()){

            //redirect
            return redirect()->route('houses.index')->with('success','house deleted successifully');
        }
        return back()->with('errors','house could not be deleted');

    }
}

resources/views/houses/create.blade.php
@extends('layouts.temp')

@section('content')

    <div class="col-md-12 col-lg-12 col-sm-12 pull-left">

        <!-- Example row of columns -->
        {{--<div class="row col-lg-12 col-md-12 col-sm-12" style="background-color: white; margin: 10px;">--}}
            <form method="post" action="{{ route('houses.store') }}">{{ csrf_field() }}

                <div class="form-group">
                    @if($houseTypes==null)
                        <input type="text" name="house_type_id" value="{{$house_type_id}}" class="form-control">
                </div>
                @endif

                @if($houseTypes !=null)
                    <div class="form-group">
                        <label for="house-content">Select House Type</label>
                        <select name="house_type_id" class="form-control">
                            @foreach($houseTypes as $houseType)
                                <option value="{{$houseType->id}}">{{$houseType->type}}</option>
                            @endforeach
                        </select>
                    </div>
            @endif

        <div class="form-group">
            <label for="house-name">House Name<span class="required">:</span></label>
            <input placeholder="Enter house name" id="house-name" required name="house_name" spellcheck="false"
                   class="form-control"/>
        </div>

        <div class="form-group">
            <label for="house-desc">House Description</label>
            <textarea placeholder="Enter description" style="resize: vertical;" id="house-content"
                      name="house_description" rows="5" spellcheck="false"
                      class="form-control autosize-target text-left"></textarea>
        </div>

        <div class="form-group">
            <label for="house-state">State<span class="required">:</span></label>
            <select required name="state" spellcheck="false" class="form-control">
                <option>Select State</option>
                <option value="Kajiado">Kajiado</option>
                <option value="Nairobi">Nairobi</option>
                <option value="Nakuru">Nakuru</option>
                <option value="Mombasa">Mombasa</option>
                <option value="Kisumu">Kisumu</option>
            </select>
            {{--<input placeholder="County" id="county" required name="state" spellcheck="false" class="form-control"/>--}}
        </div>

        <div class="form-group">
            <label for="house-city">City<span class="required">:</span></label>
            <select required name="city" spellcheck="false" class="form-control">
                <option>Select City</option>
                <option value="Rongai">Rongai</option>
                <option value="Kiserian">Kiserian</option>
                <option value="Kitengela">Kitengela</option>
                <option value="Langata">Langata</option>
                <option value="Karen">Karen</option>
            </select>
            {{--<input placeholder="City" id="city" required name="city" spellcheck="false" class="form-control"/>--}}
        </div>

        <div class="form-group">
            <label for="house-name">Area<span class="required">:</span></label>
            <select required name="area" spellcheck="false" class="form-control" placeholder="Select Area">
                <option>Select Area</option>
                <option value="Nyotu">Nyotu</option>
                <option value="Rongai">Rongai</option>
                <option value="Olekasasi">Olekasasi</option>
                <option value="Maasai lodge">Maasai lodge</option>
                <option value="Tumaini">Tumaini</option>
            </select>

            {{--<input placeholder="Area" id="house-area" required name="area" spellcheck="false" class="form-control"/>--}}
        </div>

        <div class="form-group">
            <label for="house-name">House No Rooms<span class="required">:</span></label>
            <input placeholder="Number Of Rooms" id="house-no_rooms" required name="no_rooms" spellcheck="false"
                   class="form-control"/>
        </div>

        <div class="form-group">
            <input type="hidden" id="lat" required name="latitude" spellcheck="false" class="form-control"/>
            <input type="hidden" id="long" required name="longitude" spellcheck="false" class="form-control"/>
        </div>


        <div class="form-group">
            <div style=" width:700px; height: 500px;" id="map">Asdfg</div>


        </div>
         <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Submit">


        </div>



        </form>

    </div>

    <script type="text/javascript">
        //map.js

        //Set up some of our variables.
        var map; //Will contain map object.
        var marker = false; ////Has the user plotted their location marker?

        //Function called to initialize / create the map.
        //This is called when the page has loaded.
        function initMap() {

            //The center location of our map.
            var centerOfMap = new google.maps.LatLng(-1.396249, 36.7596246);

            //Map options.
            var options = {
                center: centerOfMap, //Set center.
                zoom: 7 //The zoom value.
            };

            //Create the map object.
            map = new google.maps.Map(document.getElementById('map'), options);

            //Listen for any clicks on the map.
            google.maps.event.addListener(map, 'click', function(event) {
                //Get the location that the user clicked.
                var clickedLocation = event.latLng;
                //If the marker hasn't been added.
                if(marker === false){
                    //Create the marker.
                    marker = new google.maps.Marker({
                        position: clickedLocation,
                        map: map,
                        draggable: true //make it draggable
                    });
                    //Listen for drag events!
                    google.maps.event.addListener(marker, 'dragend', function(event){
                        markerLocation();
                    });
                } else{
                    //Marker has already been added, so just change its location.
                    marker.setPosition(clickedLocation);
                }
                //Get the marker's location.
                markerLocation();
            });
        }

        //This function will get the marker's current location and then add the lat/long
        //values to our textfields so that we can save the location.
        function markerLocation(){
            //Get location.
            var currentLocation = marker.getPosition();
            //Add lat and lng values to a field that we can save.
            document.getElementById('lat').value = currentLocation.lat(); //latitude
            document.getElementById('long').value = currentLocation.lng(); //longitude
        }


        //Load the map when the page has finished loading.
        google.maps.event.addDomListener(window, 'load', initMap);
    </script>


@endsection

resources/views/houses/edit.blade.php
@extends('layouts.app');
@section('content')
  
         <div class="col-md-9 col-lg-9 col-sm-9 pull-left">
          

        
          <!-- Example row of columns -->
          <div class="row col-lg-12 col-md-12 col-sm-12" style="background-color: white; margin: 10px;">  
             <form method="post" action="{{ route('houses.update',[$house->id]) }}">{{ csrf_field() }}

              <input type="hidden" name="_method" value="put">

              <div class="form-group">
                <label for="house-name">Name<span class="required">:</span></label>
                <input placeholder="Enter name"
                       id="house-name" required
                       name="name"
                       spellcheck="false"
                       class="form-control"
                       value="{{ $house->name}}" 

                        />

              </div>
              <div class="form-group">

                <label for="house-name">Description</label>
                <textarea placeholder="Enter description"
                       style="resize: vertical;" 
                       id="house-content" 
                       name="description"
                       rows="5"
                       spellcheck="false"
                       class="form-control autosize-target text-left"> 
                       {{ $house->description }} 

                        </textarea>
                 
              </div> 

              <div class="form-group">
                   <input type="submit" class="btn btn-primary" value="Submit">
                

              </div>
               

             </form>
             
           
          </div>
       </div>

       <div class="col-sm-3 col-md-3 col-lg-3 pull-right">
          
          <!-- <div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
          </div> -->
           <div class="sidebar-module">
            <h4>Actions</h4>
            <ol class="list-unstyled">
              <li><a href="/houses/{{$house->id}}">View houses</a></li>
              <li><a href="/houses">All houses</a></li>
            </ol>
          </div>

      <!--     <div class="sidebar-module">
            <h4>Users</h4>
            <ol class="list-unstyled">
              <li><a href="#">March 2014</a></li> 
              
            </ol>
          </div> -->
         
        </div>
         
        
    @endsection

resources/views/houses/show.blade.php
@extends('layouts.app');
@section('content')
  
         <div class="col-md-9 col-lg-9 col-sm-9 pull-left">
          <!-- The justified navigation menu is meant for single line per list item.
               Multiple lines will require custom code not provided by Bootstrap. -->
         

          <!-- Jumbotron --> 
          <div class="jumbotron">
            <h1>{{ $house->name }}</h1>
            <p class="lead">{{$house->description}}</p>
           <!--  <p><a class="btn btn-lg btn-success" href="#" role="button">Get started today</a></p> -->
          </div>

          <!-- Example row of columns -->
          <div class="row col-lg-12 col-md-12 col-sm-12" style="background-color: white; margin: 10px;">  
            <a href="/projects/create" class="pull-right btn btn-primary">Add Project</a>

            @foreach($house->projects as $project)
            <div class="col-lg-4">
              <h2>{{$project->name}}</h2>
              <p class="text-danger">{{$project->description}} </p>
              <p><a class="btn btn-primary" href="/projects/{{$project->id}}" role="button">View Projects »</a></p>
            </div>
            @endforeach
           
          </div>
       </div>

       <div class="col-sm-3 col-md-3 col-lg-3 pull-right">
          
          <!-- <div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
          </div> -->
           <div class="sidebar-module">
            <h4>Actions</h4>
            <ol class="list-unstyled">
              <li><a href="/houses/{{$house->id}}/edit">Edit</a></li></br>
              <li><a href="/projects/create/{{$house->id}}">Add Project</a></li></br>
              <li><a href="/houses">My houses</a></li></br>
              <li><a href="/houses/create/{{$house->id}}">Create new house</a></li>
 
            </br>

              <li>
                   <a 
                   href="#"
                   onclick="var result=confirm('Are you sure you wish to delete this house?');
                    if(result){
                            event.preventDefault();
                            document.getElementById('delete-form').submit();
                  } "
                   >
                   Delete
                     
                   </a>

                  <form id="delete-form" action="{{ route('houses.destroy',[$house->id]) }}" method="POST" style="display: none;">
                        <input type="hidden" name="_method" value="delete">
                        {{ csrf_field() }} 
                  </form>

              </li>
             <!--  <li><a href="#">Add new user</a></li> -->
            </ol>
          </div>

      <!--     <div class="sidebar-module">
            <h4>Users</h4>
            <ol class="list-unstyled">
              <li><a href="#">March 2014</a></li> 
              
            </ol>
          </div> -->
         
        </div>
         
        
    @endsection