routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware'=>['auth','web','member']],function(){
    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/', 'HomeController@index');
    Route::get('/client', 'HomeController@index');
    $routes_path = base_path('routes');
    $route_files = File::allFiles(base_path('routes'));
    foreach($route_files as $file){
        $path = $file->getPath();
        if($path != $routes_path){
            $file_name = $file->getFileName();
            $prefix = str_replace($file_name,'',$path);
            $prefix = str_replace($routes_path,'',$prefix);
            $file_path = $file->getPathName();
            $this->route_path = $file_path;
            $arr = explode('/',$prefix);
            $len = count($arr);
            $main_file= $arr[$len-1];
            $arr = array_map('ucwords',$arr);
            $arr = array_filter($arr);
            $ext_route = str_replace('index.route.php','',$file_name);
            $ext_route = str_replace($main_file,'',$ext_route);
            $ext_route = str_replace('.route.php','',$ext_route);
            $ext_route = str_replace('web','',$ext_route);
            if($ext_route)
                $ext_route = '/'.$ext_route;
            Route::group(['namespace'=>implode('\\',$arr),'prefix'=>strtolower($prefix.$ext_route)],function(){
                require $this->route_path;
            });
        }
    }
});

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('register/{id}','HomeController@register');

Route::resource('houses', 'HousesController');

resources/views/layouts/app.blade.php
@if(Request::ajax())
    @if(isset($_GET['t_optimized']))
        @yield('t_optimized')
    @elseif(isset($_GET['ta_optimized']))
        @yield('ta_optimized')
    @else
        <div class="col-md-10">
            <div class="card">
                <div class="card-header system-title">
                    @yield('title')
                </div>
                <div class="card-body">
                    @yield('content')
                </div>
            </div>
        </div>

        @include('common.essential_js')
    @endif
@else
    <!DOCTYPE html>
    <html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- CSRF Token -->
        <meta name="csrf-token" content="{{ csrf_token() }}">


        <title>{{ config('app.name', 'Orders') }}</title>

        <!-- Styles -->
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet">
        <link href="{{ asset('css/custom.css') }}" rel="stylesheet">
        <link href="{{ asset('fine-uploader/fine-uploader-gallery.css') }}" rel="stylesheet">
        <link href="{{ url('css/fontawesome-all.css') }}" rel="stylesheet">
        <link href="{{ url('css/custom.css') }}" rel="stylesheet">
        <link href="{{ url('chosen/chosen.css') }}" rel="stylesheet">
        <script src="{{ asset('js/jquery.min.js') }}"></script>
        <script src="{{ asset('js/jquery.history.js') }}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

        @yield('header')
        <link href="{{ URL::to('css/jquery.datetimepicker.css') }}" rel="stylesheet" type="text/css">
        <link href="{{ URL::to('sweetalert/dist/sweetalert.css') }}" rel="stylesheet">
        <script src="{{ url("ckeditor/ckeditor.js") }}"></script>
        <script src="{{ url("js/local.js") }}"></script>
        {{--<script src="https://www.gstatic.com/charts/loader.js"></script>--}}
        {{--<!-- include summernote css/js -->--}}
        {{--<link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.css" rel="stylesheet">--}}
        <style>
            /*.chat {*/
            /*width: 400px;*/
            /*}*/

            .bubble {
                background-color: #F2F2F2;
                border-radius: 5px;
                box-shadow: 0 0 6px #B2B2B2;
                display: inline-block;
                position: relative;
                vertical-align: top;
            }

            .me {
                float: left;
                margin: 5px 45px 5px 20px;
                padding: 10px 18px !important;
            }

            .you {
                float: right;
                margin-right: 8px;
                margin-bottom: 8px;
                padding: 10px 18px !important;
            }

            .replies {
                padding: 10px !important;
                margin-bottom: 10px;
                clear: both;
            }

            .sent {
                padding-left: 5px;
                clear: right;
            }

            .chat-app-form {
                padding-top: 5px;
                padding-bottom: 5px;
            }

            .support {
                width: 50%;
                padding-left: 10px;
            }

            @media screen and (min-width: 750px) {
                .header-area {
                    height: 80px;
                }
            }

        </style>

    </head>
    <body>
    @include('common.javascript')
    <div id="app">
        <div class="header-arssea">

        </div>
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand load-page" href="{{@Auth::user()->role=="client" ? '' : url(@Auth::user()->role.'') }}">
                    {{ config('app.name', 'Orders') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        @guest
                        @else
                            &nbsp;@foreach($real_menus as $menu)
                                @if($menu->type=='single' && @$menu->menus)
                                    <a class="load-page nav-link" href="{{ URL::to($menu->menus->url)  }}"><i
                                                class="fas {{ $menu->menus->icon }}"></i> {{ $menu->menus->label }}
                                        &nbsp;&nbsp;&nbsp;<span class="{{ @$menu->slug }}"></span></a>
                                @endif

                                @if($menu->type=='many')
                                    <li class="nav-item dropdown">
                                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="fas {{ $menu->icon }}"></i> {{ $menu->label }} <span
                                                    class="caret"></span>
                                        </a>

                                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                            @foreach($menu->children as $drop)
                                                @if($drop->label)
                                                    <a class="load-page dropdown-item"
                                                       href="{{ URL::to($drop->url) }}">{{ $drop->label }}</a>
                                                @endif
                                            @endforeach
                                        </div>
                                    </li>
                                @endif
                            @endforeach
                        @endguest

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        @auth
                            @if(Auth::user()->role=="client")
                                {{--<button href="{{ URL::to('orders/order/quote') }}"--}}
                                        {{--class="btn btn-success btn-sm load-page float-right"><i class="fa fa-plus"></i>&nbsp;<b> GET QUOTE</b>--}}
                                {{--</button>--}}
                            @endif
                        @else
                            {{--<button href="{{ URL::to('orders/order/new') }}"--}}
                                    {{--class="btn btn-success btn-sm load-page float-right"><i class="fa fa-plus"></i>&nbsp;<b> GET QUOTE</b>--}}
                            {{--</button>--}}
                        @endauth

                    <!-- Authentication Links -->
                        @guest
                            <li><a class="nav-link" href="{{ route('login') }}">Login</a></li>
                            <li><a class="nav-link" href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <button style="background-color:orchid; color:white" class="btn btn-sm"><span  class="notifications_count"></span> <i class="fa fa-envelope"></i></button>
                                    {{ Auth::user()->name }}
                                    <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a href="{{ url("user/profile") }}" class="load-page dropdown-item">Profile</a>
                                    <a  href="{{ url("user/notifications") }}" class="load-page dropdown-item">Notifications <span class="notifications_count"></span> </a>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        Logout
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                          style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>

                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4 row system-container justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">
                        @yield('title')
                    </div>
                    <div class="card-body">

                        @yield('content')
                    </div>
                </div>
            </div>
        </main>
    </div>

    <!-- Scripts -->
    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="{{ asset('js/fontawesome.min.js') }}"></script>
    <script src="{{ URL::to('js/jquery.datetimepicker.js') }}"></script>
    <script src="{{ URL::to('js/jquery.form.js') }}"></script>
    <script src="{{ URL::to('sweetalert/dist/sweetalert.min.js') }}"></script>
    <script src="{{ url("fine-uploader/fine-uploader.js") }}"></script>
    {{--<script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.js"></script>--}}
    <script src='{{ url("tinymce/tinymce.min.js") }}'></script>
    <script src='{{ url("chosen/chosen.jquery.js") }}'></script>


    <input type="hidden" name="material_page_loaded" value="1">
    </body>
    </html>
@endif

resources/views/layouts/temp.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>

<!-- <link href="{{ asset('css/admin.css') }}" rel="stylesheet" type="text/css">
     <link href="{{ asset('css/admintheme.css') }}" rel="stylesheet" type="text/css"> -->


</head>
<body>

<div id="app">
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name') }}
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    &nbsp;
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @guest
                        <li><a href="{{ route('login') }}">Login</a></li>
                        <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li><a href="{{ route('houses.create') }}"><i class="fa fa-building" aria-hidden="true"></i> Add A House</a></li>

                            <li><a href="{{ route('houses.index') }}"><i class="fa fa-tasks" aria-hidden="true"></i> Houses</a></li>




                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                           onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                            @endguest
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">

        <div class="page-container">
            <div class="page-sidebar-wrapper">

            </div>

            <div class="row col-md-12 pull-right">

                @yield('content')
            </div>
        </div>
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    {{--<script src="{{ asset('js/main.js') }}"></script>--}}
</body>
</html>